sudo: false
language: node_js
script:
  - curl https://raw.githubusercontent.com/shapesecurity/CLA/HEAD/cla-travis.sh | bash
  - npm run build
  - npm test
  - npm run lint
node_js:
  - "4"
  - "6"
  - "8"
